const FETCH_DOGS = 'FETCH_DOGS';
const UPDATE_PAGES = 'UPDATE_PAGES';
const UPLOAD_TEMP = 'UPLOAD_TEMP';
const SEARCH_DOGS = 'SEARCH_DOGS';
const FILTER_BY_NAME = 'FILTER_BY_NAME';
const SHOW_ALL = 'SHOW_ALL'
const UPDATE_ORDER_PARAMS = 'UPDATE_ORDER_PARAMS'
const JUMP_PAGE = 'JUMP_PAGE'
const ADD_DOG = 'ADD_DOG'
const UPDATE_SEARCH_KEY = 'UPDATE_SEARCH_KEY'

export { FETCH_DOGS, UPDATE_PAGES, UPLOAD_TEMP, SEARCH_DOGS, FILTER_BY_NAME, SHOW_ALL, UPDATE_ORDER_PARAMS, JUMP_PAGE, ADD_DOG, UPDATE_SEARCH_KEY };